version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package cache
          key: v1-cache-dependencies-{{ checksum "npm.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: npm install --frozen-lockfile
      - save_cache:
          name: Save npm package cache
          paths:
            - ~/.cache/npm
          key: v1-cache-dependencies-{{ checksum "npm.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Lint
          command: npm lint
      - run:
          name: Build
          command: npm build


